### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by andrepl** [andrepl/rivalctl#2]
```
$ rivalctl --logo-style 1
Traceback (most recent call last):
  File "/usr/local/bin/rivalctl", line 9, in <module>
    load_entry_point('rivalctl==0.1', 'console_scripts', 'rivalctl')()
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/rivalctl.py", line 67, in main
    _main(args)
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/rivalctl.py", line 47, in _main
    send_reports(reports)
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/rivalctl.py", line 19, in send_reports
    send(report)
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/rival.py", line 45, in send
    device.sendFeatureReport(report)
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/hidrawpure.py", line 128, in sendFeatureReport
    self._ioctl(_HIDIOCSFEATURE(length), buf, True)
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/hidrawpure.py", line 75, in _ioctl
    result = fcntl.ioctl(self._device, func, arg, mutate_flag)
IOError: [Errno 25] Inappropriate ioctl for device
```

**Comment by andrepl** [comment]
lsusb shows only 1 difference between the device used for development, and the device reporting the error:

Dev Device: bcdDevice            1.04

Problem Device: bcdDevice            1.08

This number indicates the product revision, so it would appear that steelseries has released a new version of this mouse which doesn't understand the same set of commands.

This might be upgradeable firmware, Will investigate further.

**Comment by andrepl** [comment]
Firmware has been upgraded, but the software still works as expected for me.  still investigating.

I have opened a support request with SteelSeries to look into the possiblity that this is a hardware variant.  results from them have been less than helpful in the past, but that seems like the best option at the time without having access to the actual problematic hardware.

**Comment by ZomBiE8192** [comment]
Has to be a hardware variant, because my friends mouse works with rivalctl, but mine doesn't. I'm not taking mine apart, because of warranty.

**Comment by andrepl** [comment]
Thanks for the confirmation. I only got the runaround from SteelSeries when asking about it.  They would not confirm or deny the existence of another version of the hardware.  I'm afraid rivalctl will never have support for this new version since I refuse to give them any more money after the nonsense I've had to deal with from their support department.
