### ISSUE TITLE
Was unable to get it to work with Python 3

### ISSUE THREAD

**Issue by bout10bucks** [andrepl/rivalctl#3]
$ rivalctl --cpi2 2000
Traceback (most recent call last):
  File "/usr/bin/rivalctl", line 9, in <module>
    load_entry_point('rivalctl==0.1', 'console_scripts', 'rivalctl')()
  File "/usr/lib/python3.4/site-packages/rivalctl-0.1-py3.4.egg/rival/rivalctl.py", line 67, in main
    _main(args)
  File "/usr/lib/python3.4/site-packages/rivalctl-0.1-py3.4.egg/rival/rivalctl.py", line 42, in _main
    reports.append(set_cpi_2(args.cpi2))
NameError: name 'set_cpi_2' is not defined

**Comment by nixi-awoo** [comment]
It has to be installed using Python 2 (for me at least).

> sudo python2 setup.py install

You will, of course, need all of the dependencies for Python2.
Also make sure you run the rivalctl command with sudo.

There is a nice package in the AUR in case you are running Arch or any Arch-based distribution.
https://aur.archlinux.org/packages/rivalctl-git/
