### ISSUE TITLE
Kubuntu error

### ISSUE THREAD

**Issue by yahoo1999** [andrepl/rivalctl#7]
Hello there! 
I own Steelseries Rival 300, and when I try to do anything with rivalctl I got this error
`Traceback (most recent call last):
  File "/usr/local/bin/rivalctl", line 9, in <module>
    load_entry_point('rivalctl==0.1', 'console_scripts', 'rivalctl')()
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/rivalctl.py", line 67, in main
    _main(args)
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/rivalctl.py", line 47, in _main
    send_reports(reports)
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/rivalctl.py", line 19, in send_reports
    send(report)
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/rival.py", line 44, in send
    device = open_device()
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/rival.py", line 33, in open_device
    return hidraw.HIDRaw(open(dev_path, 'w+'))
TypeError: coercing to Unicode: need string or buffer, NoneType found
`

I'm using Kubuntu 14.04, got the same error on Ubuntu.

**Comment by nixi-awoo** [comment]
It appears that you installed rivalctl using python2. Make sure you install it using python3 and report your results back. You might need to delete the current install:
    rm /usr/local/bin/rivalctl
    rm -rf /usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/

**Comment by nixi-awoo** [comment]
I would suggest trying out one of the forks.
I have my own fork which should work. If not, then I can fix it quickly.
https://github.com/nixi-awoo/rivalctl

Install it using python3 and everything should work just fine.
Delete your current python2 install before trying a different version.

```
rm /usr/local/bin/rivalctl
rm -rf /usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/
```

**Comment by ohyran** [comment]
I have the VERY same issue on Arch. Also I am sort of curious IF there is any interest in doodling up a GUI for it? 

Nixi: will try yours as well
