### ISSUE TITLE
rivalctl not recognized as a command

### ISSUE THREAD

**Issue by Frambooisier** [andrepl/rivalctl#9]
Hello,
I think I successfully installed rivalctl, but after installation when I try to use "rivalctl" command bash returns with command not found. Im on Open suse tumbleweed. Am I using it wrong?

Here is the output from the terminal when installing ricalctl
`flap@SFX:~/rivalcfg> sudo python setup.py install               
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/rivalcfg
copying rivalcfg/__init__.py -> build/lib/rivalcfg
copying rivalcfg/__main__.py -> build/lib/rivalcfg
copying rivalcfg/cli.py -> build/lib/rivalcfg
copying rivalcfg/command_handlers.py -> build/lib/rivalcfg
copying rivalcfg/debug.py -> build/lib/rivalcfg
copying rivalcfg/helpers.py -> build/lib/rivalcfg
copying rivalcfg/mouse.py -> build/lib/rivalcfg
copying rivalcfg/usbhid.py -> build/lib/rivalcfg
copying rivalcfg/version.py -> build/lib/rivalcfg
creating build/lib/rivalcfg/profiles
copying rivalcfg/profiles/__init__.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/hotssenseiraw.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/kanav2.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival100.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival100dota2edition.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival110.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival300.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival300acerpredator.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival300csgofadeedition.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival300csgohyperbeastedition.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival300dota2edition.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival300hpomen.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival310.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival500.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rival600.py -> build/lib/rivalcfg/profiles
copying rivalcfg/profiles/rivaldota2.py -> build/lib/rivalcfg/profiles
running install_lib
creating /usr/local/lib/python2.7
creating /usr/local/lib/python2.7/site-packages
creating /usr/local/lib/python2.7/site-packages/rivalcfg
copying build/lib/rivalcfg/__init__.py -> /usr/local/lib/python2.7/site-packages/rivalcfg
copying build/lib/rivalcfg/__main__.py -> /usr/local/lib/python2.7/site-packages/rivalcfg
copying build/lib/rivalcfg/cli.py -> /usr/local/lib/python2.7/site-packages/rivalcfg
copying build/lib/rivalcfg/command_handlers.py -> /usr/local/lib/python2.7/site-packages/rivalcfg
copying build/lib/rivalcfg/debug.py -> /usr/local/lib/python2.7/site-packages/rivalcfg
copying build/lib/rivalcfg/helpers.py -> /usr/local/lib/python2.7/site-packages/rivalcfg
copying build/lib/rivalcfg/mouse.py -> /usr/local/lib/python2.7/site-packages/rivalcfg
copying build/lib/rivalcfg/usbhid.py -> /usr/local/lib/python2.7/site-packages/rivalcfg
copying build/lib/rivalcfg/version.py -> /usr/local/lib/python2.7/site-packages/rivalcfg
creating /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/__init__.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/hotssenseiraw.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/kanav2.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival100.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival100dota2edition.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival110.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival300.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival300acerpredator.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival300csgofadeedition.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival300csgohyperbeastedition.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival300dota2edition.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival300hpomen.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival310.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival500.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rival600.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
copying build/lib/rivalcfg/profiles/rivaldota2.py -> /usr/local/lib/python2.7/site-packages/rivalcfg/profiles
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/__main__.py to __main__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/cli.py to cli.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/command_handlers.py to command_handlers.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/debug.py to debug.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/helpers.py to helpers.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/mouse.py to mouse.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/usbhid.py to usbhid.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/version.py to version.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/hotssenseiraw.py to hotssenseiraw.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/kanav2.py to kanav2.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival.py to rival.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival100.py to rival100.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival100dota2edition.py to rival100dota2edition.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival110.py to rival110.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival300.py to rival300.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival300acerpredator.py to rival300acerpredator.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival300csgofadeedition.py to rival300csgofadeedition.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival300csgohyperbeastedition.py to rival300csgohyperbeastedition.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival300dota2edition.py to rival300dota2edition.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival300hpomen.py to rival300hpomen.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival310.py to rival310.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival500.py to rival500.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rival600.py to rival600.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/rivalcfg/profiles/rivaldota2.py to rivaldota2.pyc
running install_egg_info
running egg_info
creating rivalcfg.egg-info
writing requirements to rivalcfg.egg-info/requires.txt
writing rivalcfg.egg-info/PKG-INFO
writing top-level names to rivalcfg.egg-info/top_level.txt
writing dependency_links to rivalcfg.egg-info/dependency_links.txt
writing entry points to rivalcfg.egg-info/entry_points.txt
writing manifest file 'rivalcfg.egg-info/SOURCES.txt'
reading manifest file 'rivalcfg.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.rst'
writing manifest file 'rivalcfg.egg-info/SOURCES.txt'
Copying rivalcfg.egg-info to /usr/local/lib/python2.7/site-packages/rivalcfg-3.6.1-py2.7.egg-info
running install_scripts
Installing rivalcfg script to /usr/local/bin
Installing udev rules...
Done!
`

**Comment by flozz** [comment]
Hello,

Reading your output, it seems you installed `rivalcfg` and not `rivalctl`. To check if it work and if it detect you mouse, type the following command:

    rivalcfg -l

if you encounter an issue, please report it on the project page : https://github.com/flozz/rivalcfg/

**Comment by Frambooisier** [comment]
The out put of rivalcfg -l is:
`flap@SFX:~> rivalcfg -l
Traceback (most recent call last):
  File "/usr/local/bin/rivalcfg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'hidapi>=0.7.99.post20' distribution was not found and is required by rivalcfg
`

**Comment by flozz** [comment]
please reopen an issue on the right project → https://github.com/flozz/rivalcfg/ 😉️
